#!/bin/sh
set -euf

# Use curl to call the Anthropic Claude API with Sonnet LLM.
#
# The choices of Claude versions that we prefer:
#
# - claude-opus-4-20250514 (pricier and stronger)
# - claude-sonnet-4-20250514 (cheaper and simpler)
#
# This script is specifically to generate summaries suitable
# for the guide books that we create for our users; each summary
# must fit on one PDF page that we format in specific ways.

content="$1 (format using paragraphs; no headers; less than 270 words)"
model="claude-sonnet-4-20250514"
max_tokens=400

data()
{
  cat <<EOF
{
	"model": "$model",
	"max_tokens": $max_tokens,
	"messages": [
	    {
	    	"role": "user", 
	    	"content": "$content"
	    }
	]
}
EOF
}

curl -s \
	--header "x-api-key: $ANTHROPIC_API_KEY" \
	--header "anthropic-version: 2023-06-01" \
	--header "content-type: application/json" \
	-X POST --data "$(data)" \
	https://api.anthropic.com/v1/messages |
	jq -r '.content[0].text'
